### ISSUE TITLE
[Bug] Extra argument orientation passed in run_entrypoint function

### ISSUE THREAD

**Issue by cmin764** [kivy/kivy-launcher#3]
Here: https://github.com/kivy/kivy-launcher/blob/master/main.py#L36
Quick fix: add an `orientation=None` keyword argument to the `run_entrypoint` function definition (and later use it if needed) or just don't pass the orientation anymore on the caller side.

**Comment by tito** [comment]
Hi, this was fixed in latest commit, sorry about that !
